<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <EnableDefaultCssBundling>true</EnableDefaultCssBundling>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\App.BLL\App.BLL.csproj" />
      <ProjectReference Include="..\App.DAL\App.DAL.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.2" />
      <PackageReference Include="Microsoft.AspNetCore.Cors" Version="2.3.9" />
      <PackageReference Include="Microsoft.AspNetCore.RateLimiting" Version="7.0.0-rc.2.22476.2" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.2">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.2" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.2">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.2" />
      <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="10.0.2" />
      <PackageReference Include="MySql.Data" Version="9.6.0" />
      <PackageReference Include="NetTools" Version="1.0.0" />
      <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.0" />
      <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="9.0.0" />
      <PackageReference Include="Sentry" Version="6.0.0" />
      <PackageReference Include="Sentry.AspNetCore" Version="6.0.0" />
      <PackageReference Include="Serilog" Version="4.3.0" />
      <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
      <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
      <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
      <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.0" />
      <PackageReference Include="Swashbuckle.AspNetCore.Swagger" Version="10.1.0" />
      <PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" Version="10.1.0" />
      <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="10.1.0" />
      <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.15.0" />
    </ItemGroup>

    <ItemGroup>
      <_ContentIncludedByDefault Remove="Views\User\Create.cshtml" />
      <_ContentIncludedByDefault Remove="Views\User\Delete.cshtml" />
      <_ContentIncludedByDefault Remove="Views\User\Details.cshtml" />
      <_ContentIncludedByDefault Remove="Views\User\Edit.cshtml" />
      <_ContentIncludedByDefault Remove="Views\User\Index.cshtml" />
      <_ContentIncludedByDefault Remove="Views\AuthToken\Create.cshtml" />
      <_ContentIncludedByDefault Remove="Views\AuthToken\Delete.cshtml" />
      <_ContentIncludedByDefault Remove="Views\AuthToken\Details.cshtml" />
      <_ContentIncludedByDefault Remove="Views\AuthToken\Edit.cshtml" />
      <_ContentIncludedByDefault Remove="Views\AuthToken\Index.cshtml" />
      <_ContentIncludedByDefault Remove="Views\RefreshToken\Create.cshtml" />
      <_ContentIncludedByDefault Remove="Views\RefreshToken\Delete.cshtml" />
      <_ContentIncludedByDefault Remove="Views\RefreshToken\Details.cshtml" />
      <_ContentIncludedByDefault Remove="Views\RefreshToken\Edit.cshtml" />
      <_ContentIncludedByDefault Remove="Views\RefreshToken\Index.cshtml" />
    </ItemGroup>

    <ItemGroup>
      <Content Include="..\.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
    </ItemGroup>

    <ItemGroup>
      <Folder Include="RequestModels\School\" />
    </ItemGroup>

</Project>
