<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <TargetFramework>net10.0</TargetFramework>
        <Version>1.0.0</Version>
        <Authors>Aleksander Laasmägi</Authors>
        <Company>alaasmagi</Company>
        <PackageId>alaasmagi.Base.Contracts.Domain</PackageId>
        <Description>Base Contracts Domain package for .NET webapps</Description>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Base.Contracts.Domain</RootNamespace>
        <PackageReadmeFile>Base.NuGet.README.md</PackageReadmeFile>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.2" />
    </ItemGroup>

    <ItemGroup>
      <None Include="..\Base.NuGet.README.md" Pack="true" PackagePath="\" Visible="false" />
    </ItemGroup>

</Project>
