name: Backend - Deploy to beta server

on:
  push:
    branches:
      - beta
    paths:
      - 'backend/**'

jobs:
  deploy-beta-server:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Beta server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.BACKEND_TEST_HOST }}
          username: ${{ secrets.BACKEND_VM_USERNAME }}
          key: ${{ secrets.BACKEND_TEST_SSH }}
          script: |
            cd /home/ubuntu/educode/backend
            git pull origin beta
            sudo systemctl restart educode
            echo "Deployment complete, service restarted"